apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: notification-service
  description: service pour envoi de message et mail
spec:
  type: service
  lifecycle: production
  owner: guests
